### ISSUE TITLE
create_resources for a hash parameter?

### ISSUE THREAD

**Issue by jcpunk** [jhoblitt/puppet-udev#17]
Could a hash parameter be added to init.pp optionally create udev rules via create resources?

If possible I'd prefer to specify my needed udev rules in an ENC or Hiera.  Making a class to contain:

```
  udev::rule { '60-raw.rules':
  ensure  => present,
  content => 'ACTION=="add", KERNEL=="sda", RUN+="/bin/raw /dev/raw/raw1 %N"',
  }
```

is less elegant than setting specifics via the external source.

```
classes:
  udev:
    rules:
      60-raw.rules:
        content: ACTION=="add", KERNEL=="sda", RUN+="/bin/raw /dev/raw/raw1 %N"
```
